import type { Metadata } from "next";
import { Inter, The_Girl_Next_Door } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });
const girl = The_Girl_Next_Door({
  weight: ["400"],
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={cn(girl.className, "bg-muted")}>
        <main> {children}</main>
        <Toaster  />
      </body>
    </html>
  );
}
